name: Deploy Vue to Github Pages
on: [push]
jobs:
  build_deploy_vue:
    runs-on: ubuntu-latest
    name: Build and Deploy Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Deploy-Vue
        uses: thefrustrateddev/vue-deploy-github-pages@v1.0.0
        with:
          username: "oneminch"
          reponame: "deadlines"
          token: ${{ secrets.GITHUB_TOKEN }}
